require:
  - rubocop-rails

AllCops:
  NewCops: enable

Style/Documentation:
  Exclude:
    - db/migrate/**
    - app/controllers/*_controller.rb
    - app/models/*.rb

Metrics/BlockLength:
  Exclude:
    - spec/**/*
